# Generated by Django 3.2.4 on 2021-11-21 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currencies',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('currency_name', models.CharField(max_length=3)),
            ],
        ),
    ]
